{
  'errors': [
    "144959-efimkafeed-47533/lyceum/catalog/models.py:9:1: I202 Additional newline in a group of imports. 'from django.utils.safestring import mark_safe' is identified as Third Party and 'import django.db.models' is identified as Third Party.",
    "144959-efimkafeed-47533/lyceum/catalog/tests.py:11:1: I100 Import statements are in the wrong order. 'from django.test import TestCase' should be before 'import django.urls.exceptions'",
    "144959-efimkafeed-47533/lyceum/catalog/tests.py:11:1: I202 Additional newline in a group of imports. 'from django.test import TestCase' is identified as Third Party and 'import django.urls.exceptions' is identified as Third Party.",
    '======================================================================',
    'ERROR: test_catalog_item_page (catalog.tests.CatalogTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 23, in test_catalog_item_page',
    ' response = self.client.get(reverse("catalog:item_detail", args=[1]))',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
    ' response = super().get(path, data=data, secure=secure, headers=headers, **extra)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
    ' return self.generic(',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
    ' return self.request(**r)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
    ' self.check_exception(response)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
    ' raise exc_value',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
    ' response = get_response(request)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
    ' response = wrapped_callback(request, *callback_args, **callback_kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/views.py", line 26, in item_detail',
    ' item = Item.objects.get(pk=item_id)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method',
    ' return getattr(self.get_queryset(), name)(*args, **kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get',
    ' raise self.model.DoesNotExist(',
    'catalog.models.Item.DoesNotExist: Item matching query does not exist.',
    '----------------------------------------------------------------------',
    'Ran 26 tests in 0.231s',
    'FAILED (errors=1)',
    "Destroying test database for alias 'default'...",
    'Some of your tests is failing',
    'Some of base test is failing. Test report is attached',
    '======================================================================',
    'ERROR: test_catalog_item_endpoint_00_1 (catalog.tests.StaticURLTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 31, in test_catalog_item_endpoint',
    " response = django.test.Client().get(f'/catalog/{url}/')",
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
    ' response = super().get(path, data=data, secure=secure, headers=headers, **extra)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
    ' return self.generic(',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
    ' return self.request(**r)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
    ' self.check_exception(response)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
    ' raise exc_value',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
    ' response = get_response(request)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
    ' response = wrapped_callback(request, *callback_args, **callback_kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/views.py", line 26, in item_detail',
    ' item = Item.objects.get(pk=item_id)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method',
    ' return getattr(self.get_queryset(), name)(*args, **kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get',
    ' raise self.model.DoesNotExist(',
    'catalog.models.Item.DoesNotExist: Item matching query does not exist.',
    '======================================================================',
    'ERROR: test_catalog_item_endpoint_01_100 (catalog.tests.StaticURLTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 31, in test_catalog_item_endpoint',
    " response = django.test.Client().get(f'/catalog/{url}/')",
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
    ' response = super().get(path, data=data, secure=secure, headers=headers, **extra)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
    ' return self.generic(',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
    ' return self.request(**r)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
    ' self.check_exception(response)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
    ' raise exc_value',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
    ' response = get_response(request)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
    ' response = wrapped_callback(request, *callback_args, **callback_kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/views.py", line 26, in item_detail',
    ' item = Item.objects.get(pk=item_id)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method',
    ' return getattr(self.get_queryset(), name)(*args, **kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get',
    ' raise self.model.DoesNotExist(',
    'catalog.models.Item.DoesNotExist: Item matching query does not exist.',
    '======================================================================',
    'ERROR: test_catalog_item_endpoint_02_0 (catalog.tests.StaticURLTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 31, in test_catalog_item_endpoint',
    " response = django.test.Client().get(f'/catalog/{url}/')",
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
    ' response = super().get(path, data=data, secure=secure, headers=headers, **extra)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
    ' return self.generic(',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
    ' return self.request(**r)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
    ' self.check_exception(response)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
    ' raise exc_value',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
    ' response = get_response(request)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
    ' response = wrapped_callback(request, *callback_args, **callback_kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/views.py", line 26, in item_detail',
    ' item = Item.objects.get(pk=item_id)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method',
    ' return getattr(self.get_queryset(), name)(*args, **kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get',
    ' raise self.model.DoesNotExist(',
    'catalog.models.Item.DoesNotExist: Item matching query does not exist.',
    '----------------------------------------------------------------------',
    'Ran 34 tests in 0.197s',
    'FAILED (errors=3)',
    "Destroying test database for alias 'default'...",
    'No MainImage in catalog models',
    'Too few catalog migrations, did you delete old migrations?',
    'favicon not loaded in base template',
    'No static bootstrap in base template'
  ]
}