{
  'errors': [
    'cache not in .gitignore',
    '144959-efimkafeed-47533/lyceum/about/apps.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/about/tests.py:1:1: DALL000 Module lacks __all__.',
    "144959-efimkafeed-47533/lyceum/about/urls.py:3:1: I100 Import statements are in the wrong order. 'from django.urls import path' should be before 'import about.views' and in a different group.",
    '144959-efimkafeed-47533/lyceum/about/views.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/catalog/admin.py:1:1: DALL000 Module lacks __all__.',
    "144959-efimkafeed-47533/lyceum/catalog/admin.py:3:1: I100 Import statements are in the wrong order. 'from django.contrib import admin' should be before 'import catalog.models' and in a different group.",
    '144959-efimkafeed-47533/lyceum/catalog/apps.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/catalog/models.py:1:1: DALL000 Module lacks __all__.',
    "144959-efimkafeed-47533/lyceum/catalog/models.py:5:1: I202 Additional newline in a group of imports. 'from core.models import AbstractCatalogModel' is identified as Application and 'from catalog.validators import ValidateMustContain' is identified as Application.",
    "144959-efimkafeed-47533/lyceum/catalog/models.py:7:1: I100 Import statements are in the wrong order. 'import django.core.exceptions' should be before 'from core.models import AbstractCatalogModel' and in a different group.",
    "144959-efimkafeed-47533/lyceum/catalog/models.py:12:1: I202 Additional newline in a group of imports. 'from sorl.thumbnail import get_thumbnail' is identified as Third Party and 'from django.utils.safestring import mark_safe' is identified as Third Party.",
    '144959-efimkafeed-47533/lyceum/catalog/models.py:29:73: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/catalog/models.py:48:73: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/catalog/models.py:84:79: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/catalog/models.py:96:66: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/catalog/tests.py:1:1: DALL000 Module lacks __all__.',
    "144959-efimkafeed-47533/lyceum/catalog/tests.py:3:1: I100 Import statements are in the wrong order. 'import django.core.exceptions' should be before 'from catalog.models import Category, Item, Tag' and in a different group.",
    "144959-efimkafeed-47533/lyceum/catalog/tests.py:5:1: I100 Import statements are in the wrong order. 'from django.test import TestCase' should be before 'import django.urls.exceptions'",
    '144959-efimkafeed-47533/lyceum/catalog/tests.py:21:62: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/catalog/tests.py:32:66: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/catalog/tests.py:43:66: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/catalog/urls.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/catalog/validators.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/catalog/validators.py:20:54: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/catalog/views.py:1:1: DALL000 Module lacks __all__.',
    "144959-efimkafeed-47533/lyceum/catalog/views.py:3:1: I100 Import statements are in the wrong order. 'from django.http import HttpResponse' should be before 'from catalog.models import Images, Item' and in a different group.",
    "144959-efimkafeed-47533/lyceum/catalog/views.py:27:1: F811 redefinition of unused 'item_list' from line 9",
    '144959-efimkafeed-47533/lyceum/catalog/views.py:37:14: C812 missing trailing comma',from sorl.thumbnail import get_thumbnail,
    '144959-efimkafeed-47533/lyceum/core/apps.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/core/models.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/core/models.py:6:78: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/core/models.py:9:68: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/homepage/apps.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/homepage/tests.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/homepage/views.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/lyceum/middleware.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/lyceum/settings.py:80:6: C812 missing trailing comma',
    '144959-efimkafeed-47533/lyceum/lyceum/tests.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/manage.py:1:1: DALL000 Module lacks __all__.',
    '144959-efimkafeed-47533/lyceum/manage.py:14:56: C812 missing trailing comma',
    'Job test in CI/CD failed, see log below.',
    '\x1b[0KRunning with gitlab-runner 16.3.0 (8ec04662)\x1b[0;m\n\x1b[0K on gitlab-lyceum1 vNUPFXKh, system ID: s_c3359bea3864\x1b[0;m\nsection_start:1698143546:prepare_executor\r\x1b[0K\x1b[0K\x1b[36;1mPreparing the "docker" executor\x1b[0;m\x1b[0;m\n\x1b[0KUsing Docker executor with image python:3 ...\x1b[0;m\n\x1b[0KPulling docker image python:3 ...\x1b[0;m\n\x1b[0KUsing docker image sha256:17e65561fd2c7ecae6297c2cc049960607ff94f92f6a1ca3857f94569fc9c199 for python:3 with digest python@sha256:2586dd7abe015eeb6673bc66d18f0a628a997c293b41268bc981e826bc0b5a92 ...\x1b[0;m\nsection_end:1698143550:prepare_executor\r\x1b[0Ksection_start:1698143550:prepare_script\r\x1b[0K\x1b[0K\x1b[36;1mPreparing environment\x1b[0;m\x1b[0;m\nRunning on runner-vnupfxkh-project-1271-concurrent-0 via gitlab-lyceum...\nsection_end:1698143552:prepare_script\r\x1b[0Ksection_start:1698143552:get_sources\r\x1b[0K\x1b[0K\x1b[36;1mGetting source from Git repository\x1b[0;m\x1b[0;m\n\x1b[32;1mFetching changes with git depth set to 20...\x1b[0;m\nInitialized empty Git repository in /builds/django_2023/students/144959-efimkafeed-47533/.git/\n\x1b[32;1mCreated fresh repository.\x1b[0;m\n\x1b[32;1mChecking out 9974c60c as detached HEAD (ref is main)...\x1b[0;m\n\n\x1b[32;1mSkipping Git submodules setup\x1b[0;m\nsection_end:1698143557:get_sources\r\x1b[0Ksection_start:1698143557:step_script\r\x1b[0K\x1b[0K\x1b[36;1mExecuting "step_script" stage of the job script\x1b[0;m\x1b[0;m\n\x1b[0KUsing docker image sha256:17e65561fd2c7ecae6297c2cc049960607ff94f92f6a1ca3857f94569fc9c199 for python:3 with digest python@sha256:2586dd7abe015eeb6673bc66d18f0a628a997c293b41268bc981e826bc0b5a92 ...\x1b[0;m\n\x1b[32;1m$ pip install -r requirements/test.txt\x1b[0;m\nCollecting Django==4.2.6 (from -r requirements/test.txt (line 1))\n Obtaining dependency information for Django==4.2.6 from https://files.pythonhosted.org/packages/b9/45/707dfc56f381222c1c798503546cb390934ab246fc45b5051ef66e31099c/Django-4.2.6-py3-none-any.whl.metadata\n Downloading Django-4.2.6-py3-none-any.whl.metadata (4.1 kB)\nCollecting python-dotenv==1.0.0 (from -r requirements/test.txt (line 2))\n Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)\nCollecting django-cleanup==8.0.0 (from -r requirements/test.txt (line 3))\n Obtaining dependency information for django-cleanup==8.0.0 from https://files.pythonhosted.org/packages/dc/dd/b01ca962e49608c9053e3a5c41aabd5bd0668f221b73bcc4ec9f73f53e11/django_cleanup-8.0.0-py2.py3-none-any.whl.metadata\n Downloading django_cleanup-8.0.0-py2.py3-none-any.whl.metadata (10 kB)\nCollecting django-debug-toolbar==4.2.0 (from -r requirements/test.txt (line 4))\n Obtaining dependency information for django-debug-toolbar==4.2.0 from https://files.pythonhosted.org/packages/f7/5c/fffae0d49d0b9d6a0782540e172272edf70493588ec9fca10b01a3a75c3e/django_debug_toolbar-4.2.0-py3-none-any.whl.metadata\n Downloading django_debug_toolbar-4.2.0-py3-none-any.whl.metadata (3.8 kB)\nCollecting black==23.9.1 (from -r requirements/test.txt (line 5))\n Obtaining dependency information for black==23.9.1 from https://files.pythonhosted.org/packages/28/c7/150de595f9e5ee1efffeb398acfac3e37d218171100049c77e494326dc4b/black-23.9.1-py3-none-any.whl.metadata\n Downloading black-23.9.1-py3-none-any.whl.metadata (65 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.1/65.1 kB 932.8 kB/s eta 0:00:00\nCollecting flake8==6.1.0 (from -r requirements/test.txt (line 6))\n Obtaining dependency information for flake8==6.1.0 from https://files.pythonhosted.org/packages/b0/24/bbf7175ffc47cb3d3e1eb523ddb23272968359dfcf2e1294707a2bf12fc4/flake8-6.1.0-py2.py3-none-any.whl.metadata\n Downloading flake8-6.1.0-py2.py3-none-any.whl.metadata (3.8 kB)\nCollecting flake8-quotes==3.3.2 (from -r requirements/test.txt (line 7))\n Downloading flake8-quotes-3.3.2.tar.gz (12 kB)\n Preparing metadata (setup.py): started\n Preparing metadata (setup.py): finished with status \'done\'\nCollecting pytest==7.4.2 (from -r requirements/test.txt (line 8))\n Obtaining dependency information for pytest==7.4.2 from https://files.pythonhosted.org/packages/df/d0/e192c4275aecabf74faa1aacd75ef700091913236ec78b1a98f62a2412ee/pytest-7.4.2-py3-none-any.whl.metadata\n Downloading pytest-7.4.2-py3-none-any.whl.metadata (7.9 kB)\nCollecting pep8-naming==0.13.3 (from -r requirements/test.txt (line 9))\n Downloading pep8_naming-0.13.3-py3-none-any.whl (8.5 kB)\nCollecting sorl-thumbnail==12.10.0 (from -r requirements/test.txt (line 10))\n Obtaining dependency information for sorl-thumbnail==12.10.0 from https://files.pythonhosted.org/packages/0f/3d/464f51555b21e22ef656d0d855718d9729785c8bad6420f8e0620968bf02/sorl_thumbnail-12.10.0-py3-none-any.whl.metadata\n Downloading sorl_thumbnail-12.10.0-py3-none-any.whl.metadata (8.4 kB)\nCollecting Pillow==10.1.0 (from -r requirements/test.txt (line 11))\n Obtaining dependency information for Pillow==10.1.0 from https://files.pythonhosted.org/packages/44/ed/a6f7dcd6631ec55b8d26c6a8bca762b04b7025daa3aa67e860a886abed89/Pillow-10.1.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata\n Downloading Pillow-10.1.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.5 kB)\nCollecting asgiref<4,>=3.6.0 (from Django==4.2.6->-r requirements/test.txt (line 1))\n Obtaining dependency information for asgiref<4,>=3.6.0 from https://files.pythonhosted.org/packages/9b/80/b9051a4a07ad231558fcd8ffc89232711b4e618c15cb7a392a17384bbeef/asgiref-3.7.2-py3-none-any.whl.metadata\n Downloading asgiref-3.7.2-py3-none-any.whl.metadata (9.2 kB)\nCollecting sqlparse>=0.3.1 (from Django==4.2.6->-r requirements/test.txt (line 1))\n Downloading sqlparse-0.4.4-py3-none-any.whl (41 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 896.1 kB/s eta 0:00:00\nCollecting click>=8.0.0 (from black==23.9.1->-r requirements/test.txt (line 5))\n Obtaining dependency information for click>=8.0.0 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata\n Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)\nCollecting mypy-extensions>=0.4.3 (from black==23.9.1->-r requirements/test.txt (line 5))\n Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)\nCollecting packaging>=22.0 (from black==23.9.1->-r requirements/test.txt (line 5))\n Obtaining dependency information for packaging>=22.0 from https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl.metadata\n Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)\nCollecting pathspec>=0.9.0 (from black==23.9.1->-r requirements/test.txt (line 5))\n Obtaining dependency information for pathspec>=0.9.0 from https://files.pythonhosted.org/packages/b4/2a/9b1be29146139ef459188f5e420a66e835dda921208db600b7037093891f/pathspec-0.11.2-py3-none-any.whl.metadata\n Downloading pathspec-0.11.2-py3-none-any.whl.metadata (19 kB)\nCollecting platformdirs>=2 (from black==23.9.1->-r requirements/test.txt (line 5))\n Obtaining dependency information for platformdirs>=2 from https://files.pythonhosted.org/packages/56/29/3ec311dc18804409ecf0d2b09caa976f3ae6215559306b5b530004e11156/platformdirs-3.11.0-py3-none-any.whl.metadata\n Downloading platformdirs-3.11.0-py3-none-any.whl.metadata (11 kB)\nCollecting mccabe<0.8.0,>=0.7.0 (from flake8==6.1.0->-r requirements/test.txt (line 6))\n Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)\nCollecting pycodestyle<2.12.0,>=2.11.0 (from flake8==6.1.0->-r requirements/test.txt (line 6))\n Obtaining dependency information for pycodestyle<2.12.0,>=2.11.0 from https://files.pythonhosted.org/packages/b1/90/a998c550d0ddd07e38605bb5c455d00fcc177a800ff9cc3dafdcb3dd7b56/pycodestyle-2.11.1-py2.py3-none-any.whl.metadata\n Downloading pycodestyle-2.11.1-py2.py3-none-any.whl.metadata (4.5 kB)\nCollecting pyflakes<3.2.0,>=3.1.0 (from flake8==6.1.0->-r requirements/test.txt (line 6))\n Obtaining dependency information for pyflakes<3.2.0,>=3.1.0 from https://files.pythonhosted.org/packages/00/e9/1e1fd7fae559bfd07704991e9a59dd1349b72423c904256c073ce88a9940/pyflakes-3.1.0-py2.py3-none-any.whl.metadata\n Downloading pyflakes-3.1.0-py2.py3-none-any.whl.metadata (3.5 kB)\nCollecting iniconfig (from pytest==7.4.2->-r requirements/test.txt (line 8))\n Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)\nCollecting pluggy<2.0,>=0.12 (from pytest==7.4.2->-r requirements/test.txt (line 8))\n Obtaining dependency information for pluggy<2.0,>=0.12 from https://files.pythonhosted.org/packages/05/b8/42ed91898d4784546c5f06c60506400548db3f7a4b3fb441cba4e5c17952/pluggy-1.3.0-py3-none-any.whl.metadata\n Downloading pluggy-1.3.0-py3-none-any.whl.metadata (4.3 kB)\nDownloading Django-4.2.6-py3-none-any.whl (8.0 MB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 19.2 MB/s eta 0:00:00\nDownloading django_cleanup-8.0.0-py2.py3-none-any.whl (10 kB)\nDownloading django_debug_toolbar-4.2.0-py3-none-any.whl (223 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 223.2/223.2 kB 11.5 MB/s eta 0:00:00\nDownloading black-23.9.1-py3-none-any.whl (182 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.6/182.6 kB 7.1 MB/s eta 0:00:00\nDownloading flake8-6.1.0-py2.py3-none-any.whl (58 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 4.4 MB/s eta 0:00:00\nDownloading pytest-7.4.2-py3-none-any.whl (324 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.5/324.5 kB 29.8 MB/s eta 0:00:00\nDownloading sorl_thumbnail-12.10.0-py3-none-any.whl (41 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.8/41.8 kB 2.0 MB/s eta 0:00:00\nDownloading Pillow-10.1.0-cp312-cp312-manylinux_2_28_x86_64.whl (3.6 MB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 33.7 MB/s eta 0:00:00\nDownloading asgiref-3.7.2-py3-none-any.whl (24 kB)\nDownloading click-8.1.7-py3-none-any.whl (97 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 7.3 MB/s eta 0:00:00\nDownloading packaging-23.2-py3-none-any.whl (53 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 6.8 MB/s eta 0:00:00\nDownloading pathspec-0.11.2-py3-none-any.whl (29 kB)\nDownloading platformdirs-3.11.0-py3-none-any.whl (17 kB)\nDownloading pluggy-1.3.0-py3-none-any.whl (18 kB)\nDownloading pycodestyle-2.11.1-py2.py3-none-any.whl (31 kB)\nDownloading pyflakes-3.1.0-py2.py3-none-any.whl (62 kB)\n ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 11.4 MB/s eta 0:00:00\nBuilding wheels for collected packages: flake8-quotes\n Building wheel for flake8-quotes (setup.py): started\n Building wheel for flake8-quotes (setup.py): finished with status \'done\'\n Created wheel for flake8-quotes: filename=flake8_quotes-3.3.2-py3-none-any.whl size=8616 sha256=8ac80caaf26db26006792403144352978a0c493f8f04c2bf807275710fa38065\n Stored in directory: /root/.cache/pip/wheels/8f/c4/71/8670f61b546212d5841784ee8748497014af46aeffb375bcd4\nSuccessfully built flake8-quotes\nInstalling collected packages: django-cleanup, sqlparse, sorl-thumbnail, python-dotenv, pyflakes, pycodestyle, pluggy, platformdirs, Pillow, pathspec, packaging, mypy-extensions, mccabe, iniconfig, click, asgiref, pytest, flake8, Django, black, pep8-naming, flake8-quotes, django-debug-toolbar\nSuccessfully installed Django-4.2.6 Pillow-10.1.0 asgiref-3.7.2 black-23.9.1 click-8.1.7 django-cleanup-8.0.0 django-debug-toolbar-4.2.0 flake8-6.1.0 flake8-quotes-3.3.2 iniconfig-2.0.0 mccabe-0.7.0 mypy-extensions-1.0.0 packaging-23.2 pathspec-0.11.2 pep8-naming-0.13.3 platformdirs-3.11.0 pluggy-1.3.0 pycodestyle-2.11.1 pyflakes-3.1.0 pytest-7.4.2 python-dotenv-1.0.0 sorl-thumbnail-12.10.0 sqlparse-0.4.4\nWARNING: Running pip as the \'root\' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\n[notice] A new release of pip is available: 23.2.1 -> 23.3.1\n[notice] To update, run: pip install --upgrade pip\n\x1b[32;1m$ mv test.env .env\x1b[0;m\n\x1b[32;1m$ cd lyceum\x1b[0;m\n\x1b[32;1m$ python manage.py test\x1b[0;m\nCreating test database for alias \'default\'...\nFound 26 test(s).\nSystem check identified no issues (0 silenced).\n...E........EE............\n======================================================================\nERROR: test_catalog_item_page (catalog.tests.CatalogTests.test_catalog_item_page)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n File "/builds/django_2023/students/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 15, in test_catalog_item_page\n response = self.client.get(reverse("catalog:item_detail", args=[1]))\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/usr/local/lib/python3.12/site-packages/django/test/client.py", line 927, in get\n response = super().get(path, data=data, secure=secure, headers=headers, **extra)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/usr/local/lib/python3.12/site-packages/django/test/client.py", line 457, in get\n return self.generic(\n ^^^^^^^^^^^^^\n File "/usr/local/lib/python3.12/site-packages/django/test/client.py", line 609, in generic\n return self.request(**r)\n ^^^^^^^^^^^^^^^^^\n File "/usr/local/lib/python3.12/site-packages/django/test/client.py", line 891, in request\n self.check_exception(response)\n File "/usr/local/lib/python3.12/site-packages/django/test/client.py", line 738, in check_exception\n raise exc_value\n File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner\n response = get_response(request)\n ^^^^^^^^^^^^^^^^^^^^^\n File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response\n response = wrapped_callback(request, *callback_args, **callback_kwargs)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/builds/django_2023/students/144959-efimkafeed-47533/lyceum/catalog/views.py", line 43, in item_detail\n item = Item.objects.get(pk=item_id)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/usr/local/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method\n return getattr(self.get_queryset(), name)(*args, **kwargs)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "/usr/local/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get\n raise self.model.DoesNotExist(\ncatalog.models.Item.DoesNotExist: Item matching query does not exist.\n\n======================================================================\nERROR: test_correct_creation_no_tags (catalog.tests.ItemModelsTests.test_correct_creation_no_tags)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n File "/builds/django_2023/students/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 128, in test_correct_creation_no_tags\n self.item.full_clean()\n File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1502, in full_clean\n raise ValidationError(errors)\ndjango.core.exceptions.ValidationError: {\'main_image\': [\'Это поле не может быть пустым.\']}\n\n======================================================================\nERROR: test_correct_item_creation (catalog.tests.ItemModelsTests.test_correct_item_creation)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n File "/builds/django_2023/students/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 79, in test_correct_item_creation\n self.item.full_clean()\n File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1502, in full_clean\n raise ValidationError(errors)\ndjango.core.exceptions.ValidationError: {\'main_image\': [\'Это поле не может быть пустым.\']}\n\n----------------------------------------------------------------------\nRan 26 tests in 0.166s\n\nFAILED (errors=3)\nDestroying test database for alias \'default\'...\nsection_end:1698143599:step_script\r\x1b[0Ksection_start:1698143599:cleanup_file_variables\r\x1b[0K\x1b[0K\x1b[36;1mCleaning up project directory and file based variables\x1b[0;m\x1b[0;m\nsection_end:1698143601:cleanup_file_variables\r\x1b[0K\x1b[31;1mERROR: Job failed: exit code 1\n\x1b[0;m\n',
    'Errors while running in PROD mode and getting requests',
    'Wrong content for `http://localhost:8432/`: want b\'\\xd0\\xa1\\xd0\\xbf\\xd0\\xb8\\xd1\\x81\\xd0\\xbe\\xd0\\xba \\xd1\\x82\\xd0\\xbe\\xd0\\xb2\\xd0\\xb0\\xd1\\x80\\xd0\\xbe\\xd0\\xb2\' got <!DOCTYPE html>\n<!DOCTYPE html>\n<html lang="ru">\n <head>\n <meta charset="UTF-8">\n <title> Главная </title>\n \n <link rel="shortcut icon" href="/static/img/favicon.ico">\n <link rel="stylesheet" href="/static/css/bootstrap.css">\n <link rel="stylesheet" href="/static/css/base.css">\n <script src="/static/js/bootstrap.js"></script>\n </head>\n <body>\n <!DOCTYPE html>\n\n<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">\n <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">\n <img src="/static/img/cat-boba-tea.jpg" width="60" alt="Картинка кота, пьющего чай боба">\n </a>\n <div align="left">\n <button class="btn btn-secondary rounded-pill px-2" type="button" onclick="ToggleTheme()">Переключение темы</button>\n &nbsp\n </div>\n <script>\n function ToggleTheme() {\n var element = document.body;\n element.classList.toggle("dark-mode");\n }\n </script>\n \n <ul class="nav nav-pills">\n <li class="nav-item"><a href="/" class="nav-link active">Главная</a></li>\n <li class="nav-item"><a href="/catalog/" class="nav-link ">Каталог</a></li>\n <li class="nav-item"><a href="/about/" class="nav-link ">О нас</a></li>\n </ul>\n \n</header>\n <main>\n \n\n <h1 align="center">Главная страница сайта</h1>\n <div align="center">\n <h3>Занимаемся продажей пищевых и бытовых товаров с 2023, подробнее со списком вы можете в каталоге.</h3>\n </div>\n <br>\n <div align="center">\n <a href="/catalog/">\n <button class="btn btn-lg btn-info rounded-pill px-3" type="button">ТЫК (Каталог)</button>\n </a>\n </div>\n\n </main>\n <!DOCTYPE html>\n\n<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">\n <p class="col-md-4 mb-0 text-body-secondary">&copy; 2023 000 "Дробь"</p>\n\n <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">\n <img src="/static/img/cat-in-tea.jpg" width="240" alt="Картинка кота в чае">\n </a>\n\n <ul class="nav col-md-4 justify-content-end">\n <li class="nav-item"><a href="/" class="nav-link px-2 text-body-secondary">Главная</a></li>\n <li class="nav-item"><a href="/catalog/" class="nav-link px-2 text-body-secondary">Каталог</a></li>\n <li class="nav-item"><a href="/about/" class="nav-link px-2 text-body-secondary">О нас</a></li>\n </ul>\n </footer>\n </body>\n</html>',
    'Collecting Django==4.2.6',
    ' Using cached Django-4.2.6-py3-none-any.whl (8.0 MB)',
    'Collecting django-cleanup==8.0.0',
    ' Using cached django_cleanup-8.0.0-py2.py3-none-any.whl (10 kB)',
    'Collecting python-dotenv==1.0.0',
    ' Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)',
    'Collecting sorl-thumbnail==12.10.0',
    ' Using cached sorl_thumbnail-12.10.0-py3-none-any.whl (41 kB)',
    'Collecting Pillow==10.1.0',
    ' Using cached Pillow-10.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.6 MB)',
    'Collecting sqlparse>=0.3.1',
    ' Using cached sqlparse-0.4.4-py3-none-any.whl (41 kB)',
    'Collecting asgiref<4,>=3.6.0',
    ' Using cached asgiref-3.7.2-py3-none-any.whl (24 kB)',
    'Collecting typing-extensions>=4',
    ' Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)',
    'Installing collected packages: django-cleanup, typing-extensions, sqlparse, sorl-thumbnail, python-dotenv, Pillow, asgiref, Django',
    'Successfully installed Django-4.2.6 Pillow-10.1.0 asgiref-3.7.2 django-cleanup-8.0.0 python-dotenv-1.0.0 sorl-thumbnail-12.10.0 sqlparse-0.4.4 typing-extensions-4.8.0',
    'Requirement already satisfied: Django==4.2.6 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 1)) (4.2.6)',
    'Requirement already satisfied: python-dotenv==1.0.0 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 2)) (1.0.0)',
    'Requirement already satisfied: django-cleanup==8.0.0 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 3)) (8.0.0)',
    'Collecting django-debug-toolbar==4.2.0',
    ' Using cached django_debug_toolbar-4.2.0-py3-none-any.whl (223 kB)',
    'Collecting black==23.9.1',
    ' Downloading black-23.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)',
    ' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 5.3 MB/s eta 0:00:00',
    'Collecting flake8==6.1.0',
    ' Using cached flake8-6.1.0-py2.py3-none-any.whl (58 kB)',
    'Collecting flake8-quotes==3.3.2',
    ' Using cached flake8_quotes-3.3.2-py3-none-any.whl',
    'Collecting pytest==7.4.2',
    ' Downloading pytest-7.4.2-py3-none-any.whl (324 kB)',
    ' ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.5/324.5 KB 30.0 MB/s eta 0:00:00',
    'Collecting pep8-naming==0.13.3',
    ' Using cached pep8_naming-0.13.3-py3-none-any.whl (8.5 kB)',
    'Requirement already satisfied: sorl-thumbnail==12.10.0 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 10)) (12.10.0)',
    'Requirement already satisfied: Pillow==10.1.0 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 11)) (10.1.0)',
    'Requirement already satisfied: sqlparse>=0.3.1 in ./venv/lib/python3.10/site-packages (from Django==4.2.6->-r requirements/test.txt (line 1)) (0.4.4)',
    'Requirement already satisfied: asgiref<4,>=3.6.0 in ./venv/lib/python3.10/site-packages (from Django==4.2.6->-r requirements/test.txt (line 1)) (3.7.2)',
    'Collecting mypy-extensions>=0.4.3',
    ' Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)',
    'Collecting platformdirs>=2',
    ' Using cached platformdirs-3.11.0-py3-none-any.whl (17 kB)',
    'Requirement already satisfied: typing-extensions>=4.0.1 in ./venv/lib/python3.10/site-packages (from black==23.9.1->-r requirements/test.txt (line 5)) (4.8.0)',
    'Collecting pathspec>=0.9.0',
    ' Using cached pathspec-0.11.2-py3-none-any.whl (29 kB)',
    'Collecting click>=8.0.0',
    ' Using cached click-8.1.7-py3-none-any.whl (97 kB)',
    'Collecting tomli>=1.1.0',
    ' Using cached tomli-2.0.1-py3-none-any.whl (12 kB)',
    'Collecting packaging>=22.0',
    ' Using cached packaging-23.2-py3-none-any.whl (53 kB)',
    'Collecting mccabe<0.8.0,>=0.7.0',
    ' Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)',
    'Collecting pycodestyle<2.12.0,>=2.11.0',
    ' Using cached pycodestyle-2.11.1-py2.py3-none-any.whl (31 kB)',
    'Collecting pyflakes<3.2.0,>=3.1.0',
    ' Using cached pyflakes-3.1.0-py2.py3-none-any.whl (62 kB)',
    'Collecting exceptiongroup>=1.0.0rc8',
    ' Downloading exceptiongroup-1.1.3-py3-none-any.whl (14 kB)',
    'Collecting pluggy<2.0,>=0.12',
    ' Downloading pluggy-1.3.0-py3-none-any.whl (18 kB)',
    'Collecting iniconfig',
    ' Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)',
    'Installing collected packages: tomli, pyflakes, pycodestyle, pluggy, platformdirs, pathspec, packaging, mypy-extensions, mccabe, iniconfig, exceptiongroup, click, pytest, flake8, black, pep8-naming, flake8-quotes, django-debug-toolbar',
    'Successfully installed black-23.9.1 click-8.1.7 django-debug-toolbar-4.2.0 exceptiongroup-1.1.3 flake8-6.1.0 flake8-quotes-3.3.2 iniconfig-2.0.0 mccabe-0.7.0 mypy-extensions-1.0.0 packaging-23.2 pathspec-0.11.2 pep8-naming-0.13.3 platformdirs-3.11.0 pluggy-1.3.0 pycodestyle-2.11.1 pyflakes-3.1.0 pytest-7.4.2 tomli-2.0.1',
    'Found 26 test(s).',
    'System check identified no issues (0 silenced).',
    'WARNING: You are using pip version 22.0.4; however, version 23.3.1 is available.',
    "You should consider upgrading via the '/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/bin/python3 -m pip install --upgrade pip' command.",
    'WARNING: You are using pip version 22.0.4; however, version 23.3.1 is available.',
    "You should consider upgrading via the '/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/bin/python3 -m pip install --upgrade pip' command.",
    "Creating test database for alias 'default'...",
    '...E........EE............',
    '======================================================================',
    'ERROR: test_catalog_item_page (catalog.tests.CatalogTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 15, in test_catalog_item_page',
    ' response = self.client.get(reverse("catalog:item_detail", args=[1]))',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
    ' response = super().get(path, data=data, secure=secure, headers=headers, **extra)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
    ' return self.generic(',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
    ' return self.request(**r)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
    ' self.check_exception(response)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
    ' raise exc_value',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
    ' response = get_response(request)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
    ' response = wrapped_callback(request, *callback_args, **callback_kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/views.py", line 43, in item_detail',
    ' item = Item.objects.get(pk=item_id)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method',
    ' return getattr(self.get_queryset(), name)(*args, **kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get',
    ' raise self.model.DoesNotExist(',
    'catalog.models.Item.DoesNotExist: Item matching query does not exist.',
    '======================================================================',
    'ERROR: test_correct_creation_no_tags (catalog.tests.ItemModelsTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 128, in test_correct_creation_no_tags',
    ' self.item.full_clean()',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean',
    ' raise ValidationError(errors)',
    "django.core.exceptions.ValidationError: {'main_image': ['Это поле не может быть пустым.']}",
    '======================================================================',
    'ERROR: test_correct_item_creation (catalog.tests.ItemModelsTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 79, in test_correct_item_creation',
    ' self.item.full_clean()',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean',
    ' raise ValidationError(errors)',
    "django.core.exceptions.ValidationError: {'main_image': ['Это поле не может быть пустым.']}",
    '----------------------------------------------------------------------',
    'Ran 26 tests in 0.388s',
    'FAILED (errors=3)',
    "Destroying test database for alias 'default'...",
    'Some of your tests is failing',
    'Some of base test is failing. Test report is attached',
    'Collecting Django==4.2.6',
    ' Using cached Django-4.2.6-py3-none-any.whl (8.0 MB)',
    'Collecting django-cleanup==8.0.0',
    ' Using cached django_cleanup-8.0.0-py2.py3-none-any.whl (10 kB)',
    'Collecting python-dotenv==1.0.0',
    ' Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)',
    'Collecting sorl-thumbnail==12.10.0',
    ' Using cached sorl_thumbnail-12.10.0-py3-none-any.whl (41 kB)',
    'Collecting Pillow==10.1.0',
    ' Using cached Pillow-10.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.6 MB)',
    'Collecting asgiref<4,>=3.6.0',
    ' Using cached asgiref-3.7.2-py3-none-any.whl (24 kB)',
    'Collecting sqlparse>=0.3.1',
    ' Using cached sqlparse-0.4.4-py3-none-any.whl (41 kB)',
    'Collecting typing-extensions>=4',
    ' Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)',
    'Installing collected packages: django-cleanup, typing-extensions, sqlparse, sorl-thumbnail, python-dotenv, Pillow, asgiref, Django',
    'Successfully installed Django-4.2.6 Pillow-10.1.0 asgiref-3.7.2 django-cleanup-8.0.0 python-dotenv-1.0.0 sorl-thumbnail-12.10.0 sqlparse-0.4.4 typing-extensions-4.8.0',
    'Requirement already satisfied: Django==4.2.6 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 1)) (4.2.6)',
    'Requirement already satisfied: python-dotenv==1.0.0 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 2)) (1.0.0)',
    'Requirement already satisfied: django-cleanup==8.0.0 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 3)) (8.0.0)',
    'Collecting django-debug-toolbar==4.2.0',
    ' Using cached django_debug_toolbar-4.2.0-py3-none-any.whl (223 kB)',
    'Collecting black==23.9.1',
    ' Using cached black-23.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)',
    'Collecting flake8==6.1.0',
    ' Using cached flake8-6.1.0-py2.py3-none-any.whl (58 kB)',
    'Collecting flake8-quotes==3.3.2',
    ' Using cached flake8_quotes-3.3.2-py3-none-any.whl',
    'Collecting pytest==7.4.2',
    ' Using cached pytest-7.4.2-py3-none-any.whl (324 kB)',
    'Collecting pep8-naming==0.13.3',
    ' Using cached pep8_naming-0.13.3-py3-none-any.whl (8.5 kB)',
    'Requirement already satisfied: sorl-thumbnail==12.10.0 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 10)) (12.10.0)',
    'Requirement already satisfied: Pillow==10.1.0 in ./venv/lib/python3.10/site-packages (from -r requirements/test.txt (line 11)) (10.1.0)',
    'Requirement already satisfied: sqlparse>=0.3.1 in ./venv/lib/python3.10/site-packages (from Django==4.2.6->-r requirements/test.txt (line 1)) (0.4.4)',
    'Requirement already satisfied: asgiref<4,>=3.6.0 in ./venv/lib/python3.10/site-packages (from Django==4.2.6->-r requirements/test.txt (line 1)) (3.7.2)',
    'Collecting pathspec>=0.9.0',
    ' Using cached pathspec-0.11.2-py3-none-any.whl (29 kB)',
    'Collecting mypy-extensions>=0.4.3',
    ' Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)',
    'Collecting packaging>=22.0',
    ' Using cached packaging-23.2-py3-none-any.whl (53 kB)',
    'Collecting tomli>=1.1.0',
    ' Using cached tomli-2.0.1-py3-none-any.whl (12 kB)',
    'Collecting platformdirs>=2',
    ' Using cached platformdirs-3.11.0-py3-none-any.whl (17 kB)',
    'Collecting click>=8.0.0',
    ' Using cached click-8.1.7-py3-none-any.whl (97 kB)',
    'Requirement already satisfied: typing-extensions>=4.0.1 in ./venv/lib/python3.10/site-packages (from black==23.9.1->-r requirements/test.txt (line 5)) (4.8.0)',
    'Collecting mccabe<0.8.0,>=0.7.0',
    ' Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)',
    'Collecting pycodestyle<2.12.0,>=2.11.0',
    ' Using cached pycodestyle-2.11.1-py2.py3-none-any.whl (31 kB)',
    'Collecting pyflakes<3.2.0,>=3.1.0',
    ' Using cached pyflakes-3.1.0-py2.py3-none-any.whl (62 kB)',
    'Collecting pluggy<2.0,>=0.12',
    ' Using cached pluggy-1.3.0-py3-none-any.whl (18 kB)',
    'Collecting iniconfig',
    ' Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)',
    'Collecting exceptiongroup>=1.0.0rc8',
    ' Using cached exceptiongroup-1.1.3-py3-none-any.whl (14 kB)',
    'Installing collected packages: tomli, pyflakes, pycodestyle, pluggy, platformdirs, pathspec, packaging, mypy-extensions, mccabe, iniconfig, exceptiongroup, click, pytest, flake8, black, pep8-naming, flake8-quotes, django-debug-toolbar',
    'Successfully installed black-23.9.1 click-8.1.7 django-debug-toolbar-4.2.0 exceptiongroup-1.1.3 flake8-6.1.0 flake8-quotes-3.3.2 iniconfig-2.0.0 mccabe-0.7.0 mypy-extensions-1.0.0 packaging-23.2 pathspec-0.11.2 pep8-naming-0.13.3 platformdirs-3.11.0 pluggy-1.3.0 pycodestyle-2.11.1 pyflakes-3.1.0 pytest-7.4.2 tomli-2.0.1',
    'Collecting parameterized',
    ' Downloading parameterized-0.9.0-py2.py3-none-any.whl (20 kB)',
    'Installing collected packages: parameterized',
    'Successfully installed parameterized-0.9.0',
    'Found 34 test(s).',
    'System check identified no issues (0 silenced).',
    'WARNING: You are using pip version 22.0.4; however, version 23.3.1 is available.',
    "You should consider upgrading via the '/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/bin/python3 -m pip install --upgrade pip' command.",
    'WARNING: You are using pip version 22.0.4; however, version 23.3.1 is available.',
    "You should consider upgrading via the '/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/bin/python3 -m pip install --upgrade pip' command.",
    'WARNING: You are using pip version 22.0.4; however, version 23.3.1 is available.',
    "You should consider upgrading via the '/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/bin/python3 -m pip install --upgrade pip' command.",
    "Creating test database for alias 'default'...",
    '.............EEEEEE.EEE...........',
    '======================================================================',
    'ERROR: test_item_validator_0__ (catalog.tests.ModelsTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 72, in test_item_validator',
    ' item.full_clean()',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean',
    ' raise ValidationError(errors)',
    "django.core.exceptions.ValidationError: {'main_image': ['Это поле не может быть пустым.']}",
    '======================================================================',
    'ERROR: test_item_validator_1__ (catalog.tests.ModelsTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 72, in test_item_validator',
    ' item.full_clean()',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean',
    ' raise ValidationError(errors)',
    "django.core.exceptions.ValidationError: {'main_image': ['Это поле не может быть пустым.']}",
    '======================================================================',
    'ERROR: test_item_validator_2__ (catalog.tests.ModelsTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 72, in test_item_validator',
    ' item.full_clean()',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean',
    ' raise ValidationError(errors)',
    "django.core.exceptions.ValidationError: {'main_image': ['Это поле не может быть пустым.']}",
    '======================================================================',
    'ERROR: test_item_validator_3__ (catalog.tests.ModelsTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 72, in test_item_validator',
    ' item.full_clean()',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean',
    ' raise ValidationError(errors)',
    "django.core.exceptions.ValidationError: {'main_image': ['Это поле не может быть пустым.']}",
    '======================================================================',
    'ERROR: test_item_validator_4__ (catalog.tests.ModelsTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 72, in test_item_validator',
    ' item.full_clean()',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean',
    ' raise ValidationError(errors)',
    "django.core.exceptions.ValidationError: {'main_image': ['Это поле не может быть пустым.']}",
    '======================================================================',
    'ERROR: test_item_validator_5__ (catalog.tests.ModelsTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 72, in test_item_validator',
    ' item.full_clean()',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean',
    ' raise ValidationError(errors)',
    "django.core.exceptions.ValidationError: {'main_image': ['Это поле не может быть пустым.']}",
    '======================================================================',
    'ERROR: test_catalog_item_endpoint_00_1 (catalog.tests.StaticURLTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 31, in test_catalog_item_endpoint',
    " response = django.test.Client().get(f'/catalog/{url}/')",
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
    ' response = super().get(path, data=data, secure=secure, headers=headers, **extra)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
    ' return self.generic(',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
    ' return self.request(**r)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
    ' self.check_exception(response)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
    ' raise exc_value',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
    ' response = get_response(request)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
    ' response = wrapped_callback(request, *callback_args, **callback_kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/views.py", line 43, in item_detail',
    ' item = Item.objects.get(pk=item_id)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method',
    ' return getattr(self.get_queryset(), name)(*args, **kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get',
    ' raise self.model.DoesNotExist(',
    'catalog.models.Item.DoesNotExist: Item matching query does not exist.',
    '======================================================================',
    'ERROR: test_catalog_item_endpoint_01_100 (catalog.tests.StaticURLTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 31, in test_catalog_item_endpoint',
    " response = django.test.Client().get(f'/catalog/{url}/')",
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
    ' response = super().get(path, data=data, secure=secure, headers=headers, **extra)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
    ' return self.generic(',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
    ' return self.request(**r)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
    ' self.check_exception(response)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
    ' raise exc_value',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
    ' response = get_response(request)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
    ' response = wrapped_callback(request, *callback_args, **callback_kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/views.py", line 43, in item_detail',
    ' item = Item.objects.get(pk=item_id)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method',
    ' return getattr(self.get_queryset(), name)(*args, **kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get',
    ' raise self.model.DoesNotExist(',
    'catalog.models.Item.DoesNotExist: Item matching query does not exist.',
    '======================================================================',
    'ERROR: test_catalog_item_endpoint_02_0 (catalog.tests.StaticURLTests)',
    '----------------------------------------------------------------------',
    'Traceback (most recent call last):',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
    ' return func(*(a + p.args), **p.kwargs, **kw)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/tests.py", line 31, in test_catalog_item_endpoint',
    " response = django.test.Client().get(f'/catalog/{url}/')",
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
    ' response = super().get(path, data=data, secure=secure, headers=headers, **extra)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
    ' return self.generic(',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
    ' return self.request(**r)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
    ' self.check_exception(response)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
    ' raise exc_value',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
    ' response = get_response(request)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
    ' response = wrapped_callback(request, *callback_args, **callback_kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/lyceum/catalog/views.py", line 43, in item_detail',
    ' item = Item.objects.get(pk=item_id)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method',
    ' return getattr(self.get_queryset(), name)(*args, **kwargs)',
    ' File "/builds/django_2023/tasks/task-4-1/144959-efimkafeed-47533/venv/lib/python3.10/site-packages/django/db/models/query.py", line 637, in get',
    ' raise self.model.DoesNotExist(',
    'catalog.models.Item.DoesNotExist: Item matching query does not exist.',
    '----------------------------------------------------------------------',
    'Ran 34 tests in 0.180s',
    'FAILED (errors=9)',
    "Destroying test database for alias 'default'...",
    'No MainImage in catalog models',
    'No related_name in catalog models',
    'No inlines in admin',
    'Too few catalog migrations, did you delete old migrations?',
    'favicon not loaded in base template',
    'No static bootstrap in base template'
  ]
}